### ISSUE TITLE
JAXBClassLoaeder leak?

### ISSUE THREAD

**Issue by cymurg** [mjiderhamn/classloader-leak-prevention#74] opened 2017-12-18 18:11 UTC
I have some classloader leaks in my web application and start to investigate it. When I look into the paths to gc root of my application classloader ( ChangeAwareClassLoader ) i see that it has a referance from JAXBClassLoader which is loaded by WebLogic (LaunchClassLoader). When i redeploy my web application, old context could not be reclaimed by GC because of that. Do you know such a problem ?

Java 1.8 , weblogic 12.1 ( Eclipse Moxy Implementation), Spring 4.1 web application which has soap web services

![wfl7c](https://user-images.githubusercontent.com/27578868/34120754-c4634c90-e437-11e7-9f44-830642ee9cf9.png)

**Comment by mjiderhamn** [comment] 2017-12-18 19:07
Hi @cymurg and thanks for the report! It does appear that MOXy is causing a leak. I don't have experience with MOXy and cannot tell by the image alone what is causing the leak. Specifically I'd like to know which class the `JavaClassImpl` is wrapping, and which `ClassLoader` that has loaded that class.
Would it be possible for you to make a heap dump available to me?

Also, what version of MOXy are you using? Is it bundled with WebLogic, in your .war - or both?

**Comment by cymurg** [comment] 2017-12-19 18:03
MOXy version is 2.6.2 and bundled only with WebLogic. 

Here is the heap link:  https://files.fm/u/sgge37y8
I took it after three times redeploy and when application was retired.

By the way, thanks to your posts i have found another leak which apache commons dbcp caused and i have solved adding "destroy-method="close"" to datasource bean definition in spring application xml. 
I think possible jaxbClassloader leak is another problem for us.

**Comment by mjiderhamn** [comment] 2017-12-23 07:56
Thanks for the heap dump. I have it downloaded and you can remove it if you want to.

I've analyzed it and managed to "force" reproduce the issue. Although the prevention mechanism I'm experimenting with may not be applicable in the real scenario. I may need you to do some debugging on the initialization of the MOXy classes. I'll get back with details.

**Comment by cymurg** [comment] 2017-12-23 10:22
Thanks @mjiderhamn.  I will be waiting your requests for debugging. 

I also observed that after each deploy the parent classloader of JAXBClassloader changed with newest one.

**Comment by mjiderhamn** [comment] 2017-12-25 18:19
Ok, I believe I have a fix for this now. But I'd also like to report this to the MOXy team.

Could you please add breakpoints to all the constructors of `org.eclipse.persistence.internal.jaxb.JaxbClassLoader`, run the application and then let me know which constructor is used and the stacktrace at the time of constructor invocation?

Thanks in advance.

**Comment by cymurg** [comment] 2017-12-27 11:41
Hi @mjiderhamn ,

Here are the results;

used constructor :
   public JaxbClassLoader(ClassLoader nestedClassLoader, TypeMappingInfo[] types) {
	    super(nestedClassLoader);
        this.generatedClasses = new HashMap();
        if(types != null){
            for(int i=0; i<types.length; i++){
                TypeMappingInfo tmi = types[i];
                Type nextType = tmi.getType();
                if(nextType == null){
                    throw org.eclipse.persistence.exceptions.JAXBException.nullTypeOnTypeMappingInfo(tmi.getXmlTagName());
                }
                if (nextType instanceof Class) {
                    generatedClasses.put(((Class)nextType).getName(), nextType);
                }
            }
        }		
	}

call stack :
Thread [pool-17-thread-1] (Suspended (breakpoint at line 74 in JaxbClassLoader))	
	JaxbClassLoader.<init>(ClassLoader, TypeMappingInfo[]) line: 74	
	JAXBContext$TypeMappingInfoInput.createContextState() line: 1096	
	JAXBContext.<init>(JAXBContext$JAXBContextInput) line: 192	
	JAXBContextFactory.createContext(TypeMappingInfo[], Map, ClassLoader) line: 165	
	JAXBContextFactory.newContext(BindingInfo) line: 186	
	BindingContextFactory.getBindingContextFromSpi(List<BindingContextFactory>, BindingInfo) line: 207	
	BindingContextFactory.create(BindingInfo) line: 176	
	AbstractSEIModelImpl$1.run() line: 222	
	AbstractSEIModelImpl$1.run() line: 195	
	AccessController.doPrivileged(PrivilegedExceptionAction<T>) line: not available [native method]	
	SOAPSEIModel(AbstractSEIModelImpl).createJAXBContext() line: 195	
	SOAPSEIModel(AbstractSEIModelImpl).postProcess() line: 110	
	RuntimeModeler.buildRuntimeModel() line: 325	
	DatabindingImpl.<init>(DatabindingProviderImpl, DatabindingConfig) line: 99	
	DatabindingProviderImpl.create(DatabindingConfig) line: 74	
	DatabindingProviderImpl.create(DatabindingConfig) line: 58	
	DatabindingFactoryImpl.createRuntime(DatabindingConfig) line: 120	
	WLSProvider$ServiceDelegateImpl(WSServiceDelegate).buildRuntimeModel(QName, QName, Class, WSDLPort, WebServiceFeatureList) line: 882	
	WLSProvider$ServiceDelegateImpl(WSServiceDelegate).createSEIPortInfo(QName, Class, WebServiceFeatureList) line: 899	
	WLSProvider$ServiceDelegateImpl(WSServiceDelegate).addSEI(QName, Class, WebServiceFeatureList) line: 862	
	WLSProvider$ServiceDelegateImpl(WSServiceDelegate).getPort(WSEndpointReference, QName, Class<T>, WebServiceFeatureList) line: 451	
	WLSProvider$ServiceDelegateImpl.internalGetPort(ClientInstanceIdentity, InstanceReleaser, CreationInfo) line: 1698	
	WLSProvider$ServiceDelegateImpl$PortClientInstanceFactory.createClientInstance(ClientInstanceIdentity, Class<T2>, InstanceReleaser<T2>, CreationInfo) line: 1769	
	ClientInstancePool<T>.takeSimpleClientInstance(ClientInstanceIdentity, ClientInstance$CreationInfo) line: 389	
	ClientInstancePool<T>.take(ClientInstanceIdentity, ClientInstance$CreationInfo) line: 243	
	WLSProvider$ServiceDelegateImpl$3.apply(ClientIdentityFeature) line: 1555	
	WLSProvider$ServiceDelegateImpl$3.apply(Object) line: 1517	
	ClientIdentityRegistry.initClientIdentityFeatureAndCall(QName, WSServiceDelegate, WSEndpointReference, Class<T>, String, WebServiceFeatureList, Function<ClientIdentityFeature,R>) line: 1459	
	WLSProvider$ServiceDelegateImpl.getPort(WSEndpointReference, QName, Class<T>, WebServiceFeatureList) line: 1513	
	WLSProvider$ServiceDelegateImpl(WSServiceDelegate).getPort(QName, Class<T>, WebServiceFeature...) line: 420	
	WLSProvider$ServiceDelegateImpl.getPort(QName, Class<T>, WebServiceFeature...) line: 1477	
	WLSProvider$ServiceDelegateImpl(WSServiceDelegate).getPort(QName, Class<T>) line: 402	
	AgencyWS_Service(Service).getPort(QName, Class<T>) line: 119	
	AgencyWS_Service.getAgencyWSPort() line: 55	
	AgencyWSHandler.getSOAPPort() line: 45	
	AgencyWSCaller.getAllWebsdomAccountWrapper() line: 84	
	AgencyWSCaller.getAllAgencies() line: 54	
	WebServiceCache.loadAgency() line: 81	
	WebServiceCache.access$200(WebServiceCache) line: 17	
	WebServiceCache$1.run() line: 62	
	Executors$RunnableAdapter<T>.call() line: 511	
	FutureTask<V>.run() line: 266	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1142	
	ThreadPoolExecutor$Worker.run() line: 617	
	Thread.run() line: 745 [local variables unavailable]

**Comment by mjiderhamn** [comment] 2017-12-28 11:07
I've reported the bug [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=529270). I've also pushed my suggested fix for the problem. Would you be able to compile the library from latest sources and verify that it resolves your issue?

**Closed** 2017-12-28 11:07 UTC

**Comment by cymurg** [comment] 2017-12-28 14:46
Thanks. Ok i will but couldn't see your suggestion, where was it exactly and do you want me to make your fix on latest source and compile to test ?

**Comment by mjiderhamn** [comment] 2017-12-28 15:14
The commit in question is linked above; https://github.com/mjiderhamn/classloader-leak-prevention/commit/ac4788c6038ff6e4b70c8308bfdd7cd01cb7c197
Yes, you need to compile from sources yourself for the test.

**Comment by cymurg** [comment] 2017-12-28 16:13
Ok i will do it in a short time and report you the result :)

**Comment by cymurg** [comment] 2017-12-29 17:09
Congratulations! I have tested and saw that there was no referance from jaxbclassloader to application classloader.

Thanks to your solution we will focus other leak problems.

**Comment by mjiderhamn** [comment] 2018-01-03 08:07
I did some further tweaking since I deemed my previous attempt unsafe for a multi application environment. Would you care to test again with the latest sources?

**Comment by cymurg** [comment] 2018-01-04 13:53
It is also worked with new imporvement!

**Comment by mjiderhamn** [comment] 2018-01-15 18:24
This was included in version 2.6.0 just released to Maven Central.
